# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Factorio Mod luacheck
      uses: Roang-zero1/factorio-mod-luacheck@v1.1.0

    - uses: actions/setup-python@v1

    - name: Check Python and OS Setup
      run: |
        python -c "import sys; print(sys.version);"
        python -c "import os; print(os.getcwd()); print(os.listdir(os.curdir));"

    - run: |
        python zipper.py

    - name: Calculate Artifact File Name
      id: getfilename
      run: echo "::set-output name=file::$(ls ../*.zip)"

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: ${{ steps.getfilename.outputs.file }}

